---
- hosts: all
  become: true

  tasks:
    - copy:
        src: ./wg0.conf
        dest: /etc/wireguard/wg0.conf
    
    - name: Start WireGuard interface
      ansible.builtin.shell: 
        cmd: sudo systemctl start wg-quick@wg0